packages:
  - 'examples/*'
  - 'apps/docs'
  - 'apps/page'
  - 'packages/eslint-config'
  - 'packages/tsconfig'
  - 'packages/polyfills'
  - 'packages/core'
  - 'packages/js'
  - 'packages/react'
  - 'packages/ui'
