import type { Metadata } from 'next'
import { Inter as interFonts } from 'next/font/google'
import { cookieToInitialState } from 'wagmi'
import { headers } from 'next/headers'
import { wagmiConfig } from '@/config'
import DiditSdkProvider from '@/context'
import './globals.css'

const inter = interFonts({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(wagmiConfig, headers().get('cookie'))

  return (
    <html lang="en">
      <body className={inter.className}>
        <DiditSdkProvider initialState={initialState}>{children}</DiditSdkProvider>
      </body>
    </html>
  )
}
